import type { Metadata } from "next";
import { Poppins,Playfair_Display } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";

const geistSans = Poppins({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight:["400","500","600","700"]
});
const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
})


export const metadata: Metadata = {
  title: "Ruvheneko secondary school",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} ${playfair.variable} antialiased`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
